<?php
require_once 'template/bootstrap.php';
require "template/header.php"; ?>
<h1>JE PARRAINE</h1>

<p>LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT. <a href="HTTP://LORIPSUM.NET/" target="_BLANK">ALITER ENIM NOSMET IPSOS NOSSE NON POSSUMUS.</a> EGO VERO VOLO IN VIRTUTE VIM ESSE QUAM MAXIMAM; MEMINI ME ADESSE P. <b>DUO REGES: CONSTRUCTIO INTERRETE.</b> <b>ITAQUE CONTRA EST, AC DICITIS;</b> <b>HAEC DICUNTUR FORTASSE IEIUNIUS;</b> <i>HIC NIHIL FUIT, QUOD QUAEREREMUS.</i> SIT HOC ULTIMUM BONORUM, QUOD NUNC A ME DEFENDITUR; NON AUTEM HOC: IGITUR NE ILLUD QUIDEM. HERI, INQUAM, LUDIS COMMISSIS EX URBE PROFECTUS VENI AD VESPERUM. NON EST ENIM VITIUM IN ORATIONE SOLUM, SED ETIAM IN MORIBUS. SI EST NIHIL NISI CORPUS, SUMMA ERUNT ILLA: VALITUDO, VACUITAS DOLORIS, PULCHRITUDO, CETERA. </p>

<blockquote cite="HTTP://LORIPSUM.NET">
    AT VERO FACERE OMNIA, UT ADIPISCAMUR, QUAE SECUNDUM NATURAM SINT, ETIAM SI EA NON ASSEQUAMUR, ID ESSE ET HONESTUM ET SOLUM PER SE EXPETENDUM ET SOLUM BONUM STOICI DICUNT.
</blockquote>


<p>QUEM ENIM ARDOREM STUDII CENSETIS FUISSE IN ARCHIMEDE, QUI DUM IN PULVERE QUAEDAM DESCRIBIT ATTENTIUS, NE PATRIAM QUIDEM CAPTAM ESSE SENSERIT? HAEC QUO MODO CONVENIANT, NON SANE INTELLEGO. <b>PRIMUM IN NOSTRANE POTESTATE EST, QUID MEMINERIMUS?</b> </p>

<h2>EQUIDEM ETIAM EPICURUM, IN PHYSICIS QUIDEM, DEMOCRITEUM PUTO.</h2>

<p>POSSUMUSNE ERGO IN VITA SUMMUM BONUM DICERE, CUM ID NE IN CENA QUIDEM POSSE VIDEAMUR? NUM IGITUR EUM POSTEA CENSES ANXIO ANIMO AUT SOLLICITO FUISSE? ATQUE OMNIA QUIDEM SCIRE, CUIUSCUMQUE MODI SINT, CUPERE CURIOSORUM, DUCI VERO MAIORUM RERUM CONTEMPLATIONE AD CUPIDITATEM SCIENTIAE SUMMORUM VIRORUM EST PUTANDUM. <i>TANTA VIS ADMONITIONIS INEST IN LOCIS;</i> CUR TANTAS REGIONES BARBARORUM PEDIBUS OBIIT, TOT MARIA TRANSMISIT? ISTUD QUIDEM, INQUAM, OPTIME DICIS, SED QUAERO NONNE TIBI FACIENDUM IDEM SIT NIHIL DICENTI BONUM, QUOD NON RECTUM HONESTUMQUE SIT, RELIQUARUM RERUM DISCRIMEN OMNE TOLLENTI. <b>QUI-VERE FALSONE, QUAERERE MITTIMUS-DICITUR OCULIS SE PRIVASSE;</b> OCULORUM, INQUIT PLATO, EST IN NOBIS SENSUS ACERRIMUS, QUIBUS SAPIENTIAM NON CERNIMUS. VITAE AUTEM DEGENDAE RATIO MAXIME QUIDEM ILLIS PLACUIT QUIETA. HANC ERGO INTUENS DEBET INSTITUTUM ILLUD QUASI SIGNUM ABSOLVERE. <a href="HTTP://LORIPSUM.NET/" target="_BLANK">AN HOC USQUE QUAQUE, ALITER IN VITA?</a> EST AUTEM ETIAM ACTIO QUAEDAM CORPORIS, QUAE MOTUS ET STATUS NATURAE CONGRUENTIS TENET; QUAMQUAM AB IIS PHILOSOPHIAM ET OMNES INGENUAS DISCIPLINAS HABEMUS; </p>

<ol>
    <li>NAM DE SUMMO MOX, UT DIXI, VIDEBIMUS ET AD ID EXPLICANDUM DISPUTATIONEM OMNEM CONFEREMUS.</li>
    <li>AUDIO EQUIDEM PHILOSOPHI VOCEM, EPICURE, SED QUID TIBI DICENDUM SIT OBLITUS ES.</li>
</ol>


<p><b>DEPREHENSUS OMNEM POENAM CONTEMNET.</b> SED TU, UT DIGNUM EST TUA ERGA ME ET PHILOSOPHIAM VOLUNTATE AB ADOLESCENTULO SUSCEPTA, FAC UT METRODORI TUEARE LIBEROS. CUR HAEC EADEM DEMOCRITUS? TUM, QUINTUS ET POMPONIUS CUM IDEM SE VELLE DIXISSENT, PISO EXORSUS EST. VIDES IGITUR TE AUT EA SUMERE, QUAE NON CONCEDANTUR, AUT EA, QUAE ETIAM CONCESSA TE NIHIL IUVENT. UTRUM IGITUR PERCURRI OMNEM EPICURI DISCIPLINAM PLACET AN DE UNA VOLUPTATE QUAERI, DE QUA OMNE CERTAMEN EST? <b>PHILOSOPHI AUTEM IN SUIS LECTULIS PLERUMQUE MORIUNTUR.</b> ERGO ET AVARUS ERIT, SED FINITE, ET ADULTER, VERUM HABEBIT MODUM, ET LUXURIOSUS EODEM MODO. HAEC BENE DICUNTUR, NEC EGO REPUGNO, SED INTER SESE IPSA PUGNANT. OCTAVIO FUIT, CUM ILLAM SEVERITATEM IN EO FILIO ADHIBUIT, QUEM IN ADOPTIONEM D. CUIUS SIMILITUDINE PERSPECTA IN FORMARUM SPECIE AC DIGNITATE TRANSITUM EST AD HONESTATEM DICTORUM ATQUE FACTORUM. NAM ILLUD VEHEMENTER REPUGNAT, EUNDEM BEATUM ESSE ET MULTIS MALIS OPPRESSUM. <i>SED RESIDAMUS, INQUIT, SI PLACET.</i> <i>ID EST ENIM, DE QUO QUAERIMUS.</i> </p>

<ul>
    <li>NUNC OMNI VIRTUTI VITIUM CONTRARIO NOMINE OPPONITUR.</li>
    <li>AT CERTE GRAVIUS.</li>
    <li>NON PRORSUS, INQUIT, OMNISQUE, QUI SINE DOLORE SINT, IN VOLUPTATE, ET EA QUIDEM SUMMA, ESSE DICO.</li>
    <li>CUR IGITUR, INQUAM, RES TAM DISSIMILES EODEM NOMINE APPELLAS?</li>
    <li>ERAT ENIM RES APERTA.</li>
</ul>

<?php require  "template/footer.php" ;?>

